version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
        networks: 
            - app-network
    redis:
        image: redis
        container_name: base-redis
        ports: 
            - "8001:6379"
        environment: 
            - REDIS_URL=redis://base-redis:6379
        networks: 
            - app-network
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
        networks: 
            - app-network
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
        networks: 
            - app-network
    db:
        image: postgres:12.2
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
        networks: 
            - app-network
networks: 
    app-network:
        driver: bridge
